### ISSUE TITLE
Ambiguous Rule Exception

### ISSUE THREAD

**Issue by matinnuhamunada** [NBChub/snakemake-UmetaFlow#4]
Found this error, which is the conflict between rule `sirius` and `sirius_csifingerid`:
```
AmbiguousRuleException:
Rules sirius and sirius_csifingerid are ambiguous for the file results/SIRIUS/Collinuskirromycin.mzTab.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
        sirius: samples=Collinuskirromycin
        sirius_csifingerid: samples=Collinuskirromycin
Expected input files:
        sirius: results/preprocessed/Collinuskirromycin.featureXML results/precursorcorrection/Collinuskirromycin.mzML resources/Contents/MacOS/sirius data/mzML/Collinuskirromycin.mzML
        sirius_csifingerid: results/preprocessed/Collinuskirromycin.featureXML results/precursorcorrection/Collinuskirromycin.mzML resources/Contents/MacOS/sirius data/mzML/Collinuskirromycin.mzMLExpected output files:
        sirius: results/SIRIUS/Collinuskirromycin.mzTab
        sirius_csifingerid: results/SIRIUS/Collinuskirromycin.mzTab results/CSIFingerID/Collinuskirromycin.mzTab
```

Found the same error for rule `df_sirius` and `df_sirius_csifingerid`:
```
AmbiguousRuleException:
Rules df_sirius and df_sirius_csifingerid are ambiguous for the file results/dataframes/sirius_output/sirius_Collinuskirromycin.csv.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
        df_sirius: samples=Collinuskirromycin
        df_sirius_csifingerid: samples=Collinuskirromycin
Expected input files:
        df_sirius: results/SIRIUS/Collinuskirromycin.mzTab
        df_sirius_csifingerid: results/SIRIUS/Collinuskirromycin.mzTab results/CSIFingerID/Collinuskirromycin.mzTabExpected output files:
        df_sirius: results/dataframes/sirius_output/sirius_Collinuskirromycin.csv
        df_sirius_csifingerid: results/dataframes/sirius_output/sirius_Collinuskirromycin.csv results/dataframes/CSIFingerID_output/csi_Collinuskirromycin.csv
```

The error is caused by a shared output file that are generated by both rules:
```
rule sirius_csifingerid:
    input: 
        "results/preprocessed/{samples}.featureXML",
        "results/precursorcorrection/{samples}.mzML", 
        "resources/Contents/MacOS/sirius",
        "data/mzML/{samples}.mzML"
    output:
        #"results/SIRIUS/{samples}.mzTab",
        "results/CSIFingerID/{samples}.mzTab"

rule sirius:
    input: 
        "results/preprocessed/{samples}.featureXML",
        "results/precursorcorrection/{samples}.mzML", 
        "resources/Contents/MacOS/sirius",
        "data/mzML/{samples}.mzML"
    output:
        "results/SIRIUS/{samples}.mzTab"
```

I fixed this error by giving a comment to the output `"results/SIRIUS/{samples}.mzTab",` in rule `sirius_csifingerid` (also for the df version of each rules). But I don't know if those are what the script supposed to do.
